[package]
name = "reflective_pile_unsafe"
version = "0.1.0"
edition = "2021"

[dependencies]
pile = { version = "0.1.0", path = "../pile" }
retour = { version = "0.3.1", features = ["static-detour"] }
